---
- hosts: agents

  become: True

  tasks:
  - name: install JDK 1.8
    yum:
      name: java-1.8.0-openjdk
      state: present
      
  - name: install tomcat
    yum:
      name: tomcat
      state: present
