---
- hosts: agents

  become: True

  tasks:
  - name: Create Docker image on Agent VM
    shell: sudo docker build --tag addressbookimage .
    args:
      chdir: /jenkinsnode/addressbook
      
  - name: Run Docker image on Agent VM
    shell: sudo docker run --name addressbookcontainer -publish 8081:8080 -itd addressbookimage:latest
    args:
      chdir: /jenkinsnode/addressbook
